version: "3"

services:
  db:
    restart: always
    image: postgres
    container_name: social_network_db
    environment:
      - POSTGRES_DB=social_network
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:$HOME/docker/volumes/postgres
  web:
    restart: always
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    container_name: social_network_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
